#server Global Configuration
jwt:
  signingKey: 'guojiajin'
  expiresTime: 604800 #7天
  bufferTime: 86400
  issuer: 'guojiajin'

mysql:
  path: 'localhost'
  port: '3306'
  config: 'charset=utf8mb4&parseTime=True&loc=Local'
  db-name: 'tiktok' #'dousheng_db'
  username: 'root'
  password: '123456'
  max-idle-conns: 10
  max-open-conns: 100
  log-mode: ""
  log-zap: false

runport:
  content: ':8080'